### ISSUE TITLE
Save replay while in pitstop

### ISSUE THREAD

**Issue by MrPig101** [DrVinnEck/ACC-DRIVE-issues#41]
**Is your feature request related to a problem? Please describe.**
Users are requesting to have their replay saved automatically after some time (at a pitstop) so they don't forget to save it manually (for longer events).

**Describe the solution you'd like**
Add a SETTING so that users can specify to "save replay on pitstop" which will attempt to press the button while your car is static in the pits (during the pitstop).

**Describe alternatives you've considered**
It's necessary to detect the save-replay button, which defaults to M

**Additional context**
Highly requested feature on Discord

**Comment by DrVinnEck** [comment]
When saving replay there might be a minor in-game lag. So we have to consider **when** this should be done.
I was thinking about one second after you stand still (motor stopped). Or in case a drive through is done to reset your stint timer, this should be like 5 meters behind your pit position to make sure you are not stopping.

When entering or leaving the pit, some tracks have a tight corner, so this might be not useful. When crossing start/finish line in the pits could be a disadvantage when the pit position is right behind it.
